apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-userauthmanagement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcuserauthmanagement
  template:
    metadata:
      labels:
        app: arcuserauthmanagement
    spec:
      containers:
        - name: arcuserauthmanagement
          image: hmaligro/arcuserauthmanagement:latest
---
apiVersion: v1
kind: Service
metadata:
  name: arcuserauthmanagement-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: arcuserauthmanagement
  ports:
    - name: arcuserauthmanagement
      protocol: TCP
      port: 80
      targetPort: 80
    - name: arcuserauthmanagementgrpc
      protocol: TCP
      port: 8004
      targetPort: 8004
